services:
    Ewll\CrudBundle\Controller\CrudController:
        tags: ['controller.service_arguments']
        calls: [[setContainer, ['@service_container']]]
        arguments:
            - '@Ewll\CrudBundle\Crud'
            - '@ewll.db.repository-provider'

#    App\Crud\Unit\:
#        resource: './../../../../../../src/Crud/Unit'
#        tags: ['crud_unit']
#        arguments: ['@ewll.db.repository-provider', '@Ewll\UserBundle\Authenticator\Authenticator']

    Ewll\CrudBundle\Crud:
        arguments:
            - '@validator'
            - '@ewll.db.repository-provider'
            - '@ewll.db.client.default'
            - '@Ewll\UserBundle\AccessRule\AccessRuleProvider'
            - '@Ewll\UserBundle\AccessRule\AccessChecker'
            - '@Ewll\UserBundle\Authenticator\Authenticator'
            - '@Ewll\CrudBundle\ReadViewCompiler\ReadViewCompiler'
            - '@Ewll\CrudBundle\Preformation\Preformator'
            - '@Ewll\CrudBundle\Form\FormErrorCompiler'
            - '@Ewll\CrudBundle\Form\FormFactory'
            - !tagged ewll_crud_unit
            - !tagged ewll_crud_unit_custom_action
            - '@translator'
            - '@service_container'

    Ewll\CrudBundle\ReadViewCompiler\ReadViewCompiler:
        arguments:
            - !tagged crud_view_transformer

    Ewll\CrudBundle\ReadViewCompiler\Transformer\DateTransformer:
        tags: ['crud_view_transformer']

    Ewll\CrudBundle\Preformation\PreformationAbstract:
        abstract: true

#    App\Crud\Preformation\:
#        resource: './../../../../../../src/Crud/Preformation'
#        parent: Ewll\CrudBundle\Preformation\PreformationAbstract
#        tags: ['crud_preformation']
#        autowire: false
#        autoconfigure: false

    Ewll\CrudBundle\Preformation\Preformator:
        arguments: ['@form.factory', !tagged crud_preformation]

    Ewll\CrudBundle\ReadViewCompiler\Transformer\EntityTransformer:
        tags: ['crud_view_transformer']
        arguments: ['@ewll.db.repository-provider']

    Ewll\CrudBundle\ReadViewCompiler\Transformer\TranslateTransformer:
        tags: ['crud_view_transformer']
        arguments: ['@translator']

    Ewll\CrudBundle\ReadViewCompiler\Transformer\MoneyTransformer:
        tags: ['crud_view_transformer']
        arguments: []

    Ewll\CrudBundle\ReadViewCompiler\Transformer\OneToManyTransformer:
        tags: ['crud_view_transformer']
        arguments: ['@ewll.db.repository-provider']

    Ewll\CrudBundle\Constraint\EntityAccessValidator:
        tags: ['validator.constraint_validator']
        arguments: ['@ewll.db.repository-provider']

    Ewll\CrudBundle\Form\FormErrorCompiler: []

    Ewll\CrudBundle\Form\FormFactory:
        arguments: ['@form.factory']
